# Generated by Django 5.0.4 on 2024-04-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calculateddata_historicaldata_portfolio_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='dataRetrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.portfolio'),
        ),
    ]
